### ISSUE TITLE
support farsi slug 

### ISSUE THREAD

**Issue by majidkm11** [AliBayat/Laravel-Categorizable#4]
How can I Change Slug to Farsi  
![image](https://user-images.githubusercontent.com/20963475/131245520-8d9d4715-82a0-4bf4-9cbe-b3e1b074aa5c.png)

**Comment by AliBayat** [comment]
this issue is fixed in the first stable release (v1.0)

just update the package with composer

```
composer update alibayat/laravel-categorizable
```

thanks for reporting
